In [6]:
pwd

'/Users/aashishchilwal/Desktop/group32-project/data/raw'

In [7]:
import pandas as pd
pd.read_csv("outbreaks.csv")

,Year,Month,State,Location,Food,Species,Status,Illnesses,Hospitalizations,Fatalities
0,2015,January,California,Restaurant,NaN,NaN,NaN,5,0.0,0.0
1,2015,January,California,Fast Food Restaurant,NaN,Norovirus unknown,Suspected,4,0.0,0.0
2,2015,January,California,Restaurant,NaN,Norovirus unknown,Suspected,3,0.0,0.0
3,2015,January,California,NaN,Breads,Unknown,Confirmed,44,0.0,0.0
4,2015,January,Colorado,Restaurant,NaN,NaN,NaN,2,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
892,2015,December,Wisconsin,Restaurant,NaN,Norovirus genogroup II,Confirmed,4,0.0,0.0
893,2015,December,Wisconsin,Private Home/Residence,Salsa,Norovirus genogroup II,Confirmed,16,0.0,0.0
894,2015,December,Wisconsin,Nursing Home/Assisted Living Facility,NaN,Norovirus genogroup II,Confirmed,43,3.0,0.0
895,2015,December,Wisconsin,Fast Food Restaurant,NaN,Norovirus genogroup II,Confirmed,5,0.0,0.0
896,2015,December,Wyoming,NaN,NaN,NaN,NaN,3,0.0,0.0